### ISSUE TITLE
Support for Marshmallow

### ISSUE THREAD

**Issue by VedavyasBhatNomadly** [Nexmo/verify-android-sdk#12]
When using the verify sdk with Marshmallow, it fails at `getDeviceId` because of `android.permission.READ_PHONE_STATE`, a dangerous permission, not being specifically asked for at runtime. Here is the stacktrace:

`java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.SecurityException: getDeviceId: Neither user 10112 nor current process has android.permission.READ_PHONE_STATE.
                                                                            at android.os.Parcel.readException(Parcel.java:1620)
                                                                            at android.os.Parcel.readException(Parcel.java:1573)
                                                                            at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4627)
                                                                            at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:713)
                                                                            at com.nexmo.sdk.core.device.DeviceProperties.getIMEI(DeviceProperties.java:140)
                                                                            at com.nexmo.sdk.core.device.DeviceProperties.getDeviceId(DeviceProperties.java:112)
                                                                            at com.nexmo.sdk.verify.core.service.TokenService$TokenTask.getTokenRequest(TokenService.java:173)
                                                                            at com.nexmo.sdk.verify.core.service.TokenService$TokenTask.doInBackground(TokenService.java:109)
                                                                            at com.nexmo.sdk.verify.core.service.TokenService$TokenTask.doInBackground(TokenService.java:83)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                            at java.lang.Thread.run(Thread.java:818)`

I'm currently solving this by asking for the permission just before calling `VerifyClient`'s `getVerifiedUser`. 
Can we expect support for Marshmallow in the near future?

**Comment by emmaChristine** [comment]
Hi,
We are working on user permission checks at runtime, and the new update verify1.0.2 will be available starting next week.
Please then follow this github repo or just search it up on maven central: http://mvnrepository.com/artifact/com.nexmo/verify

All the best,
Emma

**Comment by emmaChristine** [comment]
Hi,
Marshmallow support was added with verify:2.0.0, but the newest SDK version is now 'com.nexmo:verify:4.0.0'.

Starting with version 2.0.0 the SDK is not enforcing any permissions anymore, but allows the developer to add their own, while checking if required permissions are granted at runtime.
The integration steps are described in here
https://docs.nexmo.com/verify/verify-sdk-for-android/integration

Kind regards,
Emma
